/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
    var selCity = $(this).text();
    $("#btn").text(selCity);
    alert($(this).text());
    weatherData(selCity);
});


function weatherData(city){
  $.getJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + city + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",function(data){
	// 可以比較方便找到你要的資料在這個物件的哪個位置
	console.log (data) ;
  var date = data.query.results.channel.item.condition.date;
  $(".date").text(date);
  var weather = data.query.results.channel.item.condition.text;
  $("#weather").text(weather);
  var nowTem = data.query.results.channel.item.condition.temp;
  $(".temperature").text(Math.round((nowTem - 32) * 5 / 9));
  for(i=1; i<4; i++){
    var day = data.query.results.channel.item.forecast[i].date;
    var foreWeather = data.query.results.channel.item.forecast[i].text;
    var high = data.query.results.channel.item.forecast[i].high;
    var low = data.query.results.channel.item.forecast[i].low;
    $("#date" + i).text(date);
    $("#day" + i).text(foreWeather);
    $("#lowT" + i).text(Math.round((low - 32) * 5 / 9));
    $("#highT" + i).text(Math.round((high - 32) * 5 / 9));
    skycons.set("date", icon(weather));
    skycons.set("day"+i, icon(foreWeather));

  }
  
})
}
weatherData("臺北市");

function icon(weather){
    if( weather.indexOf("Sunny") >= 0 || weather.indexOf("Hot") >= 0 || weather.indexOf("Fair") >= 0 || weather.indexOf("Day") >= 0){
      return Skycons.CLEAR_DAY;
    }else if( weather.indexOf("Clear") >= 0 || weather.indexOf("Night") >= 0){
      return Skycons.CLEAR_NIGHT;
    }else if( weather.indexOf("Cloudy") >= 0 || weather.indexOf("Dust") >= 0 || weather.indexOf("Haze") >= 0 || weather.indexOf("Smoky") >= 0 ){
      return Skycons.CLOUDY;
    }else if( weather.indexOf("Snow") >= 0 || weather.indexOf("Hail") >= 0 ){
      return Skycons.SNOW;
    }else if( weather.indexOf("Sleet") >= 0){
      return Skycons.SLEET;
    }else if( weather.indexOf("Rain") >= 0 || weather.indexOf("Drizzle") >= 0 || weather.indexOf("Showers") >= 0){
      return Skycons.RAIN;
    }else if( weather.indexOf("Wind") >= 0 || weather.indexOf("Breezy") >= 0 || weather.indexOf("Blustery") >= 0 || weather.indexOf("Cold") >= 0){
      return Skycons.WIND;
    }else if( weather.indexOf("Foggy") >= 0 ){
      return Skycons.FOG;
    }
}
  skycons.play();   






